// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_Ap1_JamesUrena.DAL;

#nullable disable

namespace P2_Ap1_JamesUrena.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251103230453_Incial")]
    partial class Incial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("P2_Ap1_JamesUrena.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componente");

                    b.HasData(
                        new
                        {
                            ComponenteId = 1,
                            Descripcion = "Memoria 4GB",
                            Existencia = 1,
                            Precio = 1580m
                        },
                        new
                        {
                            ComponenteId = 2,
                            Descripcion = "Disco SSD 120MB",
                            Existencia = 8,
                            Precio = 4200m
                        },
                        new
                        {
                            ComponenteId = 3,
                            Descripcion = "Tarjeta de Video",
                            Existencia = 4,
                            Precio = 10000m
                        });
                });

            modelBuilder.Entity("P2_Ap1_JamesUrena.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("PedidoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("P2_Ap1_JamesUrena.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("PedidoId");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
